// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjjPcIF5XyrU88yJAQu1zzLIXKMi8TyyU',
    appId: '1:273151927050:web:eeebad700e6d3a3ced10f3',
    messagingSenderId: '273151927050',
    projectId: 'dev-studio-jay',
    authDomain: 'dev-studio-jay.firebaseapp.com',
    storageBucket: 'dev-studio-jay.firebasestorage.app',
    measurementId: 'G-9ZEGEM28WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtA67XgypCa-L6A1S76Y3-OoRhVUMr7tA',
    appId: '1:273151927050:android:f496fdd35493de34ed10f3',
    messagingSenderId: '273151927050',
    projectId: 'dev-studio-jay',
    storageBucket: 'dev-studio-jay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuDOZuWupCLFPlOUjqsy2XhMJpjeL8qRc',
    appId: '1:273151927050:ios:4efa3daaa102afbced10f3',
    messagingSenderId: '273151927050',
    projectId: 'dev-studio-jay',
    storageBucket: 'dev-studio-jay.firebasestorage.app',
    iosBundleId: 'com.example.codegate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuDOZuWupCLFPlOUjqsy2XhMJpjeL8qRc',
    appId: '1:273151927050:ios:4efa3daaa102afbced10f3',
    messagingSenderId: '273151927050',
    projectId: 'dev-studio-jay',
    storageBucket: 'dev-studio-jay.firebasestorage.app',
    iosBundleId: 'com.example.codegate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjjPcIF5XyrU88yJAQu1zzLIXKMi8TyyU',
    appId: '1:273151927050:web:a99cb0a039c49832ed10f3',
    messagingSenderId: '273151927050',
    projectId: 'dev-studio-jay',
    authDomain: 'dev-studio-jay.firebaseapp.com',
    storageBucket: 'dev-studio-jay.firebasestorage.app',
    measurementId: 'G-W7TWDZ3N1F',
  );

}